### ISSUE TITLE
Support for Scala 2.11?

### ISSUE THREAD

**Issue by gregsilin** [oncue/journal#6]
Noticed that there is support for Scala 2.11 in recent commits, but only 2.10 in released versions in Bintray.

Does that mean that 2.11 will be supported in an upcoming release fairly soon?

**Comment by timperrett** [comment]
@gregsilin we already support scala 2.11 - we had a community pull request the day after release.

**Comment by runarorama** [comment]
Would be good to push 2.11 to bintray though.

**Comment by gregsilin** [comment]
Thx @timperrett!   @runarorama they are in bintray: https://bintray.com/oncue/releases/journal/2.2.0/view#files

**Comment by timperrett** [comment]
@gregsilin do note the change of group id - we were playing around with rotating to maven central, but that requires cutting group id over to com.verizon, so for that reason i think we'll stay with oncue.journal for the time being, and as such, i've released a cross-build 2.2.1: https://bintray.com/oncue/releases/journal/2.2.1/
